sudo: false

language: node_js
node_js:
  - 8

before_install:
  - npm install coveralls

after_success:
  - npm run test:coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
